# Welcome to Jekyll!

# Site settings
title: CertStream
description: |
  Real-time global SSL certificate authority stream.<br>See SSL certs as they're issued.<br><br>Now in Beta.
owner: Cali Dog Security # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: ryan@calidog.io
url: "https://certstream.calidog.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/calidogsec
  github: https://github.com/calidog

# Build settings
markdown: kramdown
#sass:
#  style: compressed
